name: "2nd-order-Heun-unconditional" #same as the file name, try to do that for all testers

tester:
  _target_: 'testing.tester.Tester'

sampler:
  _target_: 'testing.EulerHeunSampler.EulerHeunSampler'

modes: ["unconditional"] #modes to test

checkpoint: None

sampling_params:
  same_as_training: False #if true, the sampling parameters will be the same as the ones used for training (sigma_data, sigma_min, sigma_max and rho)
  sde_hp:
    sigma_data: 0.05 #default for maestro
    sigma_min: 5e-4
    sigma_max: 1
    rho: 10
  Schurn: 30
  Snoise: 1
  Stmin: 0
  Stmax: 10
  order: 2 #order of the sampler (1 or 2)
  T: 201 #number of discretizatio steprs\
  schedule: edm

posterior_sampling:
  zeta: 0.5 #zeta for the posterior sampling

unconditional:
  num_samples: 1
  audio_len: 65536